sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: ak476881
    access-key-id: LTAI5t7oPuLGE6yiAKD8xRTr
    access-key-secret: SOFmc7UbbhQozmoqzP7kNLMXMQrvI9
  redis:
    host: localhost
    port: 6379
    #password: 123456
    database: 0
  wechat:
    appid: wx5fa0fb1923ddadd7
    secret: aa93eb16ca4673a58846acadf6dac542
